In [29]:
a=5
b=7.2
h="hola"
d='c'
q=[8,5,3]

3-element Array{Int64,1}:
 8
 5
 3

In [2]:
typeof(q)

Array{Int64,1}

In [12]:
q=[8, 5, 3]

3-element Array{Int64,1}:
 8
 5
 3

In [8]:
typeof(b), typeof(h)

(Char, String)

In [6]:
π

π = 3.1415926535897...

In [7]:
hòla="hóla!"

"hóla!"

In [10]:
t=a,b

(5, 'c')

In [11]:
typeof(t)

Tuple{Int64,Char}

In [20]:
q[1], q[3]

(8, 3)

In [22]:
rango=800:1500

800:1500

In [23]:
datos=randn(3000)

3000-element Array{Float64,1}:
  0.6839507935805687 
 -0.08076874607807719
  0.5044229768393785 
 -0.46540093065767857
  3.202957531667775  
 -0.21323340124420917
  1.0120928923384185 
 -0.4154845634936729 
  0.30823798151082044
 -1.059474649571526  
 -0.5783408884147571 
 -2.442349356625658  
  0.1112268288330156 
  ⋮                  
 -1.89962916135739   
  0.7960782630647159 
  0.4009679299855323 
 -1.6733892663033811 
 -1.2330453271594322 
 -1.1335170658550233 
 -0.4813414795244584 
  1.590948474522461  
  0.25345546135611713
  0.2564069026995014 
  0.5551638037511292 
 -0.2740129396948111 

In [24]:
subdatos=datos[rango]

701-element Array{Float64,1}:
  0.03623809346716192 
 -1.5907697423991243  
  1.5755216110579562  
  0.16672013620816398 
 -0.833090128971341   
 -1.04140729213895    
 -0.7009163523249852  
  0.16367166473861033 
  0.21519838014052753 
  0.4228762789733518  
  0.6818396922508171  
  0.2627640610453474  
 -0.2265906304961912  
  ⋮                   
  1.028157805090073   
 -1.9149235735488677  
  0.35572821668446786 
  1.5294752843589718  
 -1.5026087119891256  
  0.4441479940146701  
 -0.3814347491031165  
 -0.531769603943841   
  0.37066011523570586 
  0.030732787449465802
  0.121929332871145   
  1.5115068825344193  

In [36]:
8//3+5//9

29//9

In [37]:
typeof(8//3)

Rational{Int64}

In [41]:
matriz=randn(701,701)

701×701 Array{Float64,2}:
 -1.55958     0.391567    1.53972     …   2.58515     0.896506     1.10406  
  0.322515    0.67987    -0.054561       -0.710035    0.576108    -1.52043  
 -1.43656    -0.713508   -0.463353       -1.38116     0.487156    -0.33839  
 -0.64061     0.374047   -1.36384         1.22265     1.418       -0.817169 
 -0.0259173  -0.461233    0.266119        1.528      -0.492985     0.0501408
  1.02365     1.23977    -0.583532    …   1.15744    -0.739648     2.79387  
 -0.0354496   0.0479055   0.902812        0.228016   -0.69101     -0.346824 
 -0.119492   -0.391224   -0.00930192      1.61967    -0.764358    -0.62563  
  0.675156    0.278687    0.530899        0.676428    0.505853    -2.34991  
 -0.545704    0.194611    0.665744        0.890313   -0.00742679   0.171631 
 -0.378587    0.102517   -1.19963     …  -0.55745    -0.476031    -1.19828  
 -0.463191    0.885575    0.495184        1.38538     0.518498    -0.802343 
 -0.149106    0.271257    0.0581119      -0.793468

In [42]:
matriz*subdatos

701-element Array{Float64,1}:
  10.141362755909991  
 -49.531536939313156  
 -13.677904760567651  
 -48.8393033923271    
  15.305989503600346  
  44.83492189803038   
 -30.85659134193912   
 -29.364886403453397  
  13.997291918972918  
  13.989014561055463  
  16.769524256443656  
   4.31061273937516   
   1.4431465530656182 
   ⋮                  
  -8.456427615210602  
 -17.786594387833286  
  -6.498086256280568  
  10.40852051883395   
  18.419101637616095  
   2.266185148658103  
  -8.320864256946304  
  10.830748086767601  
   0.08959677783534288
  -5.90332849510423   
  -7.21966626782705   
 -26.81011322819601   

In [45]:
println("tu abuela, $t")

tu abuela, (5, 'c')


search: write unsafe_write iswritable lowercasefirst



```
write(io::IO, x)
write(filename::AbstractString, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream.   See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

You can write multiple values with the same `write` call. i.e. the following are equivalent:

```
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```
